### PR TITLE
Docker environment 

### PR DESCRIPTION
**Pull request by paasovaara**
Use Docker to create an environment with all required dependencies installed, so any user can build the preprocessed data.

Exclude input data and proprietary dependencies (strafica-libraries) from the build and mount them at runtime. 

usage (TODO add to readme)
- ./build-docker.sh
- ./run-docker.sh
- Rscript ./strafica/install.R
- start building the dataset..

### CODE REVIEW

**Comment by paasovaara** [comment]
Some questions @johpiip: 
- do we also want to run Python-scripts here? Then we need to install python & pipenv in the Dockerfile
- Where is the output produced? Should we create a mounting point for some output folder which would then be used to save the data to the host-machine.
- Is it enough to copy the strafica library or should it be installed somehow?

**Comment by johpiip** [comment]
Answers to your questions, @paasovaara:

- Yes, we want to run Python also. Creating new estimation datasets usually means that we add some important but missing column to our Python-created tour files (`tours/output/*.csv`).
- Output is written to `tours/output` but also to `estimation/alternatives`. Estimation alternatives are most important but tours are viewed too from time to time. Other files are created too but they are not that important... at least when everything is working. If something needs to be debugged, they would be nice to have?
- Running `install.R` in `strafica` repo installs the package. The script just runs `install.packages(".", repos=NULL, type="source")` in package root.

**Comment by johpiip** [comment]
I am quite certain now that this works. I added some fixes regarding input and output data. However, I cannot test the Docker image as my setup is not yet complete on my new laptop.

**Review by johpiip — APPROVED** [review]

**Comment by johpiip** [comment]
I am going to merge this now. We will fix any oddities in new branches.

**Pull request merged**
